name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: true
        description: nome da image docker
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ inputs.image-name }}:$(date +%s)
